### ISSUE TITLE
채용공고 등록 기능 개발

### ISSUE THREAD

**Issue by JoonheeJeong** [JoonheeJeong/wanted-pre-onboarding-backend#3]
### To-do
- [x] 앱 설정 파일 작성
- [x] 컨트롤러 테스트 작성
- [x] 컨트롤러 작성
  - [x] 요청 dto 작성
  - [x] 회사, 회원, 기술 도메인 작성
  - [x] 응답 객체 작성
- [x] 서비스 테스트 작성
  - [x] 회사, 회원, 기술 더미데이터 작성
- [x] 서비스 작성
  - [x] 채용공고, 채용공고 기술 도메인 작성
- [x] 레포지토리 테스트 작성
- [x] 레포지토리 작성
